#
# ArtifactHub: https://artifacthub.io/packages/helm/longhorn/longhorn
# GitHub: https://github.com/longhorn/longhorn/tree/master/chart
# Default Values: https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
#
global: {}

defaultSettings:
  defaultDataPath: "${__longhorn_volume_dir}"
  storageReservedPercentageForDefaultDisk: 5

persistence:
  defaultClass: false
  defaultClassReplicaCount: 1

longhornManager: {}

longhornDriver: {}

longhornUI:
  replicas: 1

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: true

ingress:
  enabled: true
  ingressClassName: nginx
  host: "${STORAGE_DOMAIN}"
  tls: true
  tlsSecret: origin-cert

metrics:
  serviceMonitor:
    enabled: false
