#
# ArtifactHub: https://artifacthub.io/packages/helm/argo/argo-cd
# GitHub: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
# Default Values: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
#
configs:
  cm:
    create: false
  secret:
    createSecret: false

  params:
    server.insecure: true

global:
  domain: "${ARGOCD_DOMAIN}"

redis:
  resources: {}
  #  limits:
  #    cpu: 200m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 64Mi

controller:
  resources: {}
  #  limits:
  #    cpu: 500m
  #    memory: 512Mi
  #  requests:
  #    cpu: 250m
  #    memory: 256Mi

dex:
  resources: {}
  #  limits:
  #    cpu: 50m
  #    memory: 64Mi
  #  requests:
  #    cpu: 10m
  #    memory: 32Mi

server:
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 50m
  #    memory: 64Mi

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - "${ARGOCD_DOMAIN}"
    paths:
      - /
    tls:
      - secretName: origin-cert
        hosts:
          - "${ARGOCD_DOMAIN}"

repoServer:
  resources: {}
  #  limits:
  #    cpu: 50m
  #    memory: 128Mi
  #  requests:
  #    cpu: 10m
  #    memory: 64Mi

applicationSet:
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

notifications:
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

commitServer:
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
